sudo: false

language: rust

matrix:
  include:
    - rust: stable
    - rust: beta

    - rust: nightly
      script:
        - cargo test
        - cargo test --no-default-features
        - cargo test --no-default-features --features=alloc
        - cargo test --no-default-features --features=alloc -- --ignored

script:
  - cargo build
  - cargo test
  - cargo test --release -- --ignored
